### ISSUE TITLE
Resources Time Warning

### ISSUE THREAD

**Issue by KingRyuShin** [ESX-Org/esx_menu_default#10] opened 2018-10-09 05:57 UTC
I'm using the lastest build of FiveM (804)
Reinstalled every script clean without any modification in the script itself
Modified only the css of esx_menu_default to change the form and color of title
But now.. when we switch fast in the menu there is a resources time warning.. what could be causing this ?

https://imgur.com/rja3vmi

**Comment by blackflash01** [comment] 2018-10-09 16:55
the same for , since last client build .

**Comment by Dragese** [comment] 2018-10-09 18:29
same problem

**Comment by sitamCZ** [comment] 2018-10-11 09:39
I can confirm same problem, even tried with latest server binaries.

**Comment by Syntasu** [comment] 2018-10-11 11:02
confirmed, having the same issue.

**Comment by Xseba360** [comment] 2018-10-11 15:17
Can confirm this as well.

**Comment by ElPumpo** [comment] 2018-10-17 18:29
Duplicate of #5

**Closed by ElPumpo** 2018-10-17 18:29 UTC
